### ISSUE TITLE
Management Summary

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#10]

**Comment by Graf-Carello** [comment]
First draft is ready for review. The text file is saved under following path on SharePoint: Dokumente\BusinessPlan\ManagementSummary_v1.docx

**Comment by tortmann** [comment]
added a comment in yellow regarding the necessity of SLAs - this aspect should also be discussed shortly during the next meeting since the revenue model also requires further discussion.

**Comment by Graf-Carello** [comment]
I added a bit of information according to your RFC. Further findings from tomorrows meeting will be implemented. So as you pointed out, we need to discuss and finalize our revenue model if possible tomorrow.

**Comment by tortmann** [comment]
thanks for the changes - exactly what I requested - as you mentioned a discussion about the details of the revenue model will follow in tomorrow's meeting

**Comment by Graf-Carello** [comment]
I added the changes to the revenue model in the document. This is corresponding with the discussion in our last meeting and with the revenue model from NSpalek. 

I uploaded the new file ManagementSummary_v2.docx on the Sharepoint.

**Comment by tortmann** [comment]
Changes are approved. Thank you. I just want to mention that when combinig the individual files into one large document the references to other chapters or files need to be adjusted accordingly.
