### ISSUE TITLE
Approval-View (Refinement)

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#100]
Refinement and refactoring according to the comments issued at the PR #90

**Comment by Graf-Carello** [comment]
Now the approval page and approval-details page are two seperate pages, and if an approver clicks on one process of the list of all processes, he gets  to the details page, where he can approve or disapprove of a process, which now works with data from the backend.

There is still a problem with the backend response concerning the approved attribute of a specific process. The backend always returns false at the moment, even if the data in the SQL DB is actually true.

And it is not fully clear to me if the review comment should just be the attribute processApproverComment (of the process itself) or if a row in the actual review table should be used for comments. Nevertheless some kind of endpoints in the backend are still needed for this.

**Comment by tortmann** [comment]
does the GET request also return "false" within the response body?

**Comment by Graf-Carello** [comment]
Yes, the GET request returns "false" within the response body, even though it should be "true" (and is actually true in the SQL-DB).
