### ISSUE TITLE
EasyBiz Logo Integration

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#104]
Logo files (png,jpg,ai,svg) can be found on Sharepoint under Documents/Development/EasyBiz_Logo

Please integrate image into the header (probably top left) and on the welcome page + favicon (favicon package zip)

Also use the Logo in the business model document (also needs finishing regarding team desc #22)

**Comment by deKilla** [comment]
I don't know how/why I'm already assigned - but I'll take care of it :) (I mean the website-part of this task)

Maybe @dietrich14 can take care of the document ... would be appreciated :)

**Comment by deKilla** [comment]
ok done - I also changed the favicon ... I pushed it into the branch logointegration-#104 but I didn't make a pull request as the entire task is not yet done

**Comment by dietrich14** [comment]
added the logo to the business plan document, version 4.1 can be found on SP 
Dokumente/BusinessPlan/easybiz_geschaeftsmodell_v4-1.pdf
