### ISSUE TITLE
Problem with API Respones from StoreService Task #30

### ISSUE THREAD

**Issue by Graf-Carello** [amarbajric/EBUSA-AIM17#105]
There is still a problem with the **backend response concerning the approved attribute** of a specific process. The backend always returns false at the moment, even if the data in the SQL DB is actually true.
So when I call the endpoint **GET localhost:10000/api/store/processes** to get all processes from the SQL-DB, the attribute approved of a process is always false.

Here is a picture of the **response I get from the API where approved is set to false:**
![api response](https://user-images.githubusercontent.com/15038288/41850099-a9087052-7883-11e8-947c-531d31195438.PNG)

And here is the actual **data directly from the SQL-DB, where approved is set to true/1:**
![db](https://user-images.githubusercontent.com/15038288/41850142-ca36eaec-7883-11e8-9d22-22fbcbd3ca56.PNG)

The problem may be that you are giving back some kind of default value with approved, or you are not correctly outputting the DB value from the API. I took a quick look into your Java implementations, but I am sorry I am not really familiar with your implementations. I hope this description is understandable and precise enough. So any help to this problem would be great =)

**Comment by stfnltnr** [comment]
resolved by https://github.com/amarbajric/EBUSA-AIM17/pull/115
