### ISSUE TITLE
Prepare Presentation Demo Dummy Data

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#108]
Prepare SQL statements that generate all required dataset for a proper demo during the presentation.

Requirements: fill up all tables with meaningful dummy entry also including dummy comments dummy ratings , approvals etc.

For further questions please contact me.

This will be used for the live demo to have a nice (linux-based) runnig verison of the latest dev branch version and the SQL + a short documentation will be added to the Readme tomorrow in order to provide nice dummy data for customer test runs.

**Comment by dietrich14** [comment]
ready for review - Document can be found on SP/Documents/Development/Dummy_Data/ebusa_testdata_v1

**Comment by tortmann** [comment]
v8 was the great masterpiece
