### ISSUE TITLE
Vision, Mission, Strategy

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#11]

**Comment by Graf-Carello** [comment]
First draft is ready for review. The file can be found in the BusinessPlan folder. 
Especially for the companies strategy I wasn't to sure on what to write. So I think this topic needs a bit discussing tomorrow.

**Comment by tortmann** [comment]
very nice and concise yet detailed overview. I agree with you that discussing the strategy with the team is a great idea

**Comment by Graf-Carello** [comment]
I added information about the strategy of EasyBiz. The new file VisionStrategy_v2.docx can be found on SharePoint in the BusinessPlan folder.

**Comment by tortmann** [comment]
Very well written strategy and in my opinion you covered everything. Approved (can be added to the large document)
