### ISSUE TITLE
Business Model

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#12]

**Comment by Graf-Carello** [comment]
First draft is ready for review. I tried to keep it short, since other docs like the BMC, VPC etc explain the business model in more detail. So we don't have the same information written down multiple times.

**Comment by tortmann** [comment]
please change "newly developed platform" to extended platform and giving reference to the original project. requested changes are marked in yellow in the document

**Comment by Graf-Carello** [comment]
I added the reference to the IPPR2016 project. I guess "newly developed platform" sounded cooler, but is a bit too far from the actual truth =)

**Comment by tortmann** [comment]
thanks for the changes - approved
