### ISSUE TITLE
Platform Functionality

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#15]

**Comment by tortmann** [comment]
I know you are probably not quite done with the platform functionality but I just had a quick peak at the current version. Seems great, however no matter the results, a detailed discussion with members of the dev team (@amarbajric , @loete ) especially in conjunction with the new data model #29 will be necessary

**Comment by Graf-Carello** [comment]
I discussed the functionality with @amarbajric and finished the first draft of the document now. So the file PlatformFunctionality_v1.docx is ready for review and saved on the SharePoint.

**Comment by amarbajric** [comment]
As @Graf-Carello has already mentioned, all aspects regarding the platform functionality have been discussed. Further, we have also discussed which functionalities are highly desired but left out at the beginning, because we need to first concentrate on the main platform functionality.

**Comment by tortmann** [comment]
Approved!
