### ISSUE TITLE
Risk Analysis

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#18]

**Comment by NSpalek** [comment]
Ready for review.
Can be found on SharePoint: Dokumente\BusinessPlan\Risikoanalyse_v1.xlsx
Gives an overview about the basic risks for the developement and operating phase.

To-Do:
More risks should be discussed with teammembers individually (better insight) and added to the document

**Comment by tortmann** [comment]
I would definitely evaluate "lack of competence of teammembers" as much more likely to occur than 20% - should be discussed during the next meeting

"team members not completing tasks in time" should also be included in my opinion as it influences the progess of the project escpecially relevent for te dev team and if dependancies are related to the missing/incomplete task

>To-Do:
More risks should be discussed with teammembers individually (better insight) and added to the document

I definitely agree.

**Comment by NSpalek** [comment]
I agree, this should be discussed.
The evaluation should be higher if we consider, that we use a complex basis as a starting point, which no team member has worked on before.

You're right! This is definitly a risk to be added.
Therefore I would like to interview some team members (or at least the team leaders) to add more risks I haven't thought  of by now, after our next meeting

**Comment by tortmann** [comment]
Final review and discussion will happen 24.04. 10am - will be ready shortly after this meeting

**Comment by NSpalek** [comment]
Ready for second review.
Can be found on SharePoint: Dokumente\BusinessPlan\Risikoanalyse_v2.xlsx

**Comment by tortmann** [comment]
**Approved** - final changes were discussed and reviewed during skype call 24.04. - 10:15-10:35am
