### ISSUE TITLE
Value Proposition Canvas

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#19]

**Comment by NSpalek** [comment]
Ready for review.
Can be found on SharePoint: Dokumente\BusinessPlan\ValuePropositionCanvas_v1.docx

**Comment by tortmann** [comment]
I highlighted a couple of points that should be discussed in more detail during our next team meeting to discuss their necessity or level of detail. In general however it is well done and will be approved after the some potentially minor changes following the next meeting.

**Comment by NSpalek** [comment]
Ready for second review.
Can be found on SharePoint: Dokumente\BusinessPlan\ValuePropositionCanvas_v2.docx

**Comment by Graf-Carello** [comment]
The VPC is quite good and explains the most important aspects of the value EasyBiz generates for their customers. I just corrected some small typos.

**Comment by tortmann** [comment]
Thank you for making the discussed changes. Approved (ready to be added to the large document)
