### ISSUE TITLE
SWOT - Analysis

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#20]

**Comment by NSpalek** [comment]
Ready for review.
Can be found on SharePoint: Dokumente\BusinessPlan\SWOT_v1.xlsx

Top five for every category were chosen, but it could be extended if necessary.
Document holds very detailed desrciption and information based on the template to easily extend. Can be deleted if no longer needed, but it is a nice bonus.

**Comment by tortmann** [comment]
I really liked the SWOT analysis especially the fact that you also mentioned the necessity for innovation management. Approved
