### ISSUE TITLE
Customers, Marketing, Communication

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#21]

**Comment by dietrich14** [comment]
ready for review, can be found on sharepoint in folder BusinessPlan

**Comment by tortmann** [comment]
comments marked in yellow - very well done in general - only a few additions are necessary

**Comment by tortmann** [comment]
comments marked in yellow - very well done in general - only a few additions are necessary

**Comment by dietrich14** [comment]
version 2  can be found on sharepoint in folder BusinessPlan\Kundenbindung_Marketing_Kommunikationsstrategie_v2

changes:
- added innovation-solutions to competition analysis in case of competitiors in the markt segment
- added more detailed information to the highlighted sections from v1

**Comment by tortmann** [comment]
All changes are approved. (ready to be merged)
