### ISSUE TITLE
Team Description

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#22]

**Comment by dietrich14** [comment]
ready for review, can be found on sharepoint

TODO: add further description of activities of the members of the dev team

**Comment by tortmann** [comment]
The document is fine for now but should definitely grow during the project and might need a categorization per person for each milestone to see changes throughout the project. I will move it back to "in progress" nevertheless it's hereby approved as done for Milestone 1.

**Comment by dietrich14** [comment]
added to version 4.1 of the businessplan document, newest version can be found on SP at Dokumente/BusinessPlan/easybiz_geschaeftsmodell_v4-1.pdf

added several new responsibilities of the team members
