### ISSUE TITLE
"The Transformative Business"

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#23]
6 aspects

**Comment by tortmann** [comment]
I did not quite agree with your interpretation of a few key points discussed. Therefore I left some comments marked in yellow with a request for change and if necessary further discussions during the next meeting.

**Comment by dietrich14** [comment]
version 2 can be found on sharepoint in folder BusinessPlan\The-Transformative-Business-Model_v2

changes:

- almost everything.
- I marked all the changes in yellow for better traceability of the conducted changes

**Comment by tortmann** [comment]
**Approved**
Thank you very much for marking the changes, this saved me a lot of time. All changes are very well done. I only added a second part to the very last sentence of the document by referring to innovation management as a mean of enhancing the company's agility in the future.
