### ISSUE TITLE
Extend/Adapt RBAC Service

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#40]
The `Gateway` microservice and its `AuthenticationService` need to be adapted in order to allow registration and login of users.
- Depends on tasks/issues #29 and #39

**Comment by tortmann** [comment]
Directly connected to #39

**Comment by tortmann** [comment]
ER-diagram of implemented data model: SharePoint **Documents\Development\Data_model\ippr_security_new.pdf**

### UPDATE (24.04.2018, 01:10 pm)
**Dependancies #29 and #39 are resolved and closed.**
This task should be completed asap in order to test #62 for the interim presentation 27.04.

**Comment by amarbajric** [comment]
**UPDATE - Development**
- Memory Authentication was changed
  - now the `email` and `password` need to be provided to the `/user/login` endpoint in order to login and get a valid token. (before it was `username` and `password`)

**ToDo**
@tortmann we need to discuss the initial roles tomorrow, which should be created. For registration we will need something like `normal_user` and then we can also define the other roles. Upon that, I can try to implement the registration functionality until Fr, 27.04.2018 

- Implement authentication which does not use `CachedUser` (i.e. does not use in-memory users but the ones from the database)
- Add new roles
- Add endpoint where users can register
