### ISSUE TITLE
Processstore - WelcomePage component

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#48]
On the landing page, we should also greet the visitor/guest/user with some information/data. THIS TASK SHOULD BE DONE IF TASK #45 is done/approved!
- show for example recently added processes to the store
- show processes with the best reviews
- etc.

**Comment by deKilla** [comment]
I've created a first version of this page
There are some elements that this depends on that are not yet available (process rating for example)
But you may want to take a look at the current progress to provide feedback - I wouldn't know what else to do for now.
