### ISSUE TITLE
CleanUp Repo - Delete (inactive) branches

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#61]
After the meeting the unnecessary and no longer needed feature-branches will be deleted. This should help in order to keep an overview about active (feature)branches and unused ones.

- Needs confirmation from members after plenum discussion

**Comment by tortmann** [comment]
Great idea. Maybe until then everyone has managed to actually create a feature-branch matching their currently assigned tasks ;)

**Comment by amarbajric** [comment]
**NOTE**
This issue does not require any PR. I will comment the branches which I think can be safely deleted.

**Branches safe for deletion:**
- `project-changelog-#65`
- `angular-update-#44`
  - I will create a new branch when doing further work regarding issue #44 
- `unix-running-#1`
- `spring-config-#38`
- `nativequeries-lowercase-#37`
- `mysql-docker-#4`

**ToDo**
- @tortmann, @loete, @deKilla: 
  - reviewer should review if suggested branches can be deleted from their side.
  - just leave a thumbs up if you agree or drop a comment if you disagree with your considerations.
- If approved, I will delete branches and close this issue.

**Comment by stfnltnr** [comment]
:+1:

**Comment by deKilla** [comment]
+1

**Comment by tortmann** [comment]
👍

**Comment by amarbajric** [comment]
Very nice.
Issue closed, thank you!
