### ISSUE TITLE
Login/Registration Mask - Test with new frontend

### ISSUE THREAD

**Issue by amarbajric** [amarbajric/EBUSA-AIM17#62]
**NOTE: This task depends on:**
- [x] Task #72 
- [ ] Task #73 (is not fully dependent. Consider to ONLY implement the described aspects below)

After the new frontend has been set-up, the Login/Register component should be tested.
- Implement Register form/mask and add button to the Login form/mask
- Implement basic features for the Authentication in the frontend
  - Login Page/Register should be displayed first when starting app
  - Implement Guard to not be able to navigate to other pages when not logged in (logged-in users receive a token from the backend)
  - consider using a npm module for handling the token and putting it automatically in the header for every request (i.e. https://github.com/auth0/angular2-jwt)
- Evaluate implemented features
  - Test Login
  - Test Register
  - Test Guards
  - Test JWT token handler

**Comment by deKilla** [comment]
Hab jetzt amal die register hinzugefügt und "username" im login durch email ersetzt. Dadurch das es net läuft konnt ich es leider (noch) nicht testen darum auch noch nicht im Review.
Ich hab überlegt das ganze in ein eigenes/isoliertes Projekt auszulagern um es dort zu testen aber ich denke das is so reinverankert das sich das nicht "einfach so" isolieren lässt. Schau ma dann im Meeting wie wir hier weiter vorgehen. #44 sollte mmn absolute prio haben ... da müssen wir notfalls uns zamsetzten und schauen, dass wir das hinbekommen ...

**Comment by amarbajric** [comment]
**UPDATE**
Thank you for your comment @deKilla. I would suggest to write all comments in englisch, because everyone has commented in english so far and therefore we should keep it that way. However, this is no negative point.
Furthermore, a review is NOT possible due to the fact that #44 has to be finished first.

**ToDo**
- Keep this issue in the `in progress` swimlane
- As soon as #44 is finished, consider testing your implemented functionality to ensure that everything is working
  - Best case scenario would be to wait until the backend is ready to handle the `register` functionality and THEN test your implemented feature (#39 and #40 are in need to be finished first)
- Open a pull request as soon as everything is done, tested and is working properly
  - Refer to other PRs on how to comment and add an appropriate description

**Comment by tortmann** [comment]
If possible (depending on when #39 and #40 will be finished) finalize and test #62 so that we can maybe show the working Login/Register in combination with the extended backend during the interim presentation on 27.04.

**Comment by amarbajric** [comment]
@tortmann thank you for the comment.
Yes this is very important and should be tested ASAP and if the registration endpoint is implemented in the backend!

**Comment by amarbajric** [comment]
**NOTE**
This issue/task was updated on 26th of April.
Please see the first (initial) comment of this issue/task and check out the description if you assign yourself to this task!
