### ISSUE TITLE
Data model refinement

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#82]
Detailed info will follow on 30.04.2018 after meeting

Until then see document on SharePoint:
`/Development/APs_Requirements/EBUSA_SWD_APs_29.04.18.pdf`

**Comment by amarbajric** [comment]
File can be found on SharePoint:
`\Development\Data_model\data_model_adaptions_v2.1.pdf`

**DONE:**
- included all the points which were discussed by me and @loete.
  - Roles and Rules defined
  - added considerations to the proposed ROLE/RULE scenario
  - adapted the data model excerpt in the file

**ToDo:**
- need review from @tortmann, @loete, @deKilla (if it is possible regarding the frontend auth)
- review changes for ROLE/RULE and add considerations if you have any.
