### ISSUE TITLE
Frontend Design Guideline & Documentation

### ISSUE THREAD

**Issue by tortmann** [amarbajric/EBUSA-AIM17#85]
Create a design guideline for the use of ngx-admin in this project.

For more details see document on SharePoint:
`/Development/APs_Requirements/EBUSA_SWD_APs_29.04.18.pdf`

**Comment by NSpalek** [comment]
Ready for review.
Can be found on SharePoint: Dokumente\Development\Designguide\Designguide_v1.docx

**Comment by tortmann** [comment]
reviewed and approved
